// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlX9lPhA7h_JSv3JJ2ZmCQdn68vLKhVOg',
    appId: '1:654832633382:web:a98a50c12924c08d19c8e7',
    messagingSenderId: '654832633382',
    projectId: 'curso-de-verano-be6a5',
    authDomain: 'curso-de-verano-be6a5.firebaseapp.com',
    storageBucket: 'curso-de-verano-be6a5.firebasestorage.app',
    measurementId: 'G-TPWDHH4ZEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArtsxVdFRGr0bvovENX04wI6fuMsuIZE8',
    appId: '1:654832633382:android:23b34f976cc9feb819c8e7',
    messagingSenderId: '654832633382',
    projectId: 'curso-de-verano-be6a5',
    storageBucket: 'curso-de-verano-be6a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqpzlaIXkDCtOjVxBR2IvEKVQRBQP1tvY',
    appId: '1:654832633382:ios:d839349a079d208219c8e7',
    messagingSenderId: '654832633382',
    projectId: 'curso-de-verano-be6a5',
    storageBucket: 'curso-de-verano-be6a5.firebasestorage.app',
    iosBundleId: 'com.example.cursoDeVerano',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqpzlaIXkDCtOjVxBR2IvEKVQRBQP1tvY',
    appId: '1:654832633382:ios:d839349a079d208219c8e7',
    messagingSenderId: '654832633382',
    projectId: 'curso-de-verano-be6a5',
    storageBucket: 'curso-de-verano-be6a5.firebasestorage.app',
    iosBundleId: 'com.example.cursoDeVerano',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlX9lPhA7h_JSv3JJ2ZmCQdn68vLKhVOg',
    appId: '1:654832633382:web:0fb231c819d402dd19c8e7',
    messagingSenderId: '654832633382',
    projectId: 'curso-de-verano-be6a5',
    authDomain: 'curso-de-verano-be6a5.firebaseapp.com',
    storageBucket: 'curso-de-verano-be6a5.firebasestorage.app',
    measurementId: 'G-XNSQCTM0T1',
  );

}